// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stetic {
    
    
    internal class Gui {
        
        public static void Build(object obj, System.Type type) {
            Stetic.Gui.Build(obj, type.FullName);
        }
        
        public static void Build(object obj, string id) {
            System.Collections.Hashtable bindings = new System.Collections.Hashtable();
            if ((id == "MainWindow")) {
                Gtk.Window cobj = ((Gtk.Window)(obj));
                // Widget MainWindow
                cobj.Title = "MainWindow";
                cobj.WindowPosition = ((Gtk.WindowPosition)(4));
                cobj.Events = ((Gdk.EventMask)(0));
                cobj.Name = "MainWindow";
                // Container child MainWindow.Gtk.Container+ContainerChild
                Gtk.VBox w1 = new Gtk.VBox();
                w1.Events = ((Gdk.EventMask)(0));
                w1.Name = "vbox1";
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.HBox w2 = new Gtk.HBox();
                w2.Events = ((Gdk.EventMask)(0));
                w2.Name = "hbox1";
                // Container child hbox1.Gtk.Box+BoxChild
                Gtk.Entry w3 = new Gtk.Entry();
                w3.IsEditable = true;
                w3.InvisibleChar = '●';
                w3.CanFocus = true;
                w3.Events = ((Gdk.EventMask)(0));
                w3.Name = "entry1";
                bindings["entry1"] = w3;
                w2.Add(w3);
                Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w2[w3]));
                w4.Position = 0;
                // Container child hbox1.Gtk.Box+BoxChild
                Gtk.Button w5 = new Gtk.Button();
                w5.CanFocus = true;
                w5.Events = ((Gdk.EventMask)(0));
                w5.Name = "buttonChooser";
                w5.Label = "choose";
                bindings["buttonChooser"] = w5;
                w2.Add(w5);
                Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(w2[w5]));
                w6.Position = 1;
                w6.Expand = false;
                w6.Fill = false;
                bindings["hbox1"] = w2;
                w1.Add(w2);
                Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(w1[w2]));
                w7.Position = 0;
                w7.Expand = false;
                w7.Fill = false;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.TreeView w8 = new Gtk.TreeView();
                w8.CanFocus = true;
                w8.Events = ((Gdk.EventMask)(0));
                w8.Name = "treeview";
                bindings["treeview"] = w8;
                w1.Add(w8);
                Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w1[w8]));
                w9.Position = 1;
                bindings["vbox1"] = w1;
                cobj.Add(w1);
                cobj.DefaultWidth = 400;
                cobj.DefaultHeight = 300;
                bindings["MainWindow"] = cobj;
                w3.Show();
                w5.Show();
                w2.Show();
                w8.Show();
                w1.Show();
                cobj.Show();
                cobj.DeleteEvent += ((Gtk.DeleteEventHandler)(System.Delegate.CreateDelegate(typeof(Gtk.DeleteEventHandler), cobj, "OnDeleteEvent")));
                w3.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnEntry1Activated")));
                w5.Clicked += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnButtonChooserClicked")));
            }
            System.Reflection.FieldInfo[] fields = obj.GetType().GetFields(((System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic) | System.Reflection.BindingFlags.Instance));
            for (int n = 0; (n < fields.Length); n = (n + 1)) {
                System.Reflection.FieldInfo field = fields[n];
                object widget = bindings[field.Name];
                if (((widget != null) && field.FieldType.IsInstanceOfType(widget))) {
                    field.SetValue(obj, widget);
                }
            }
        }
    }
    
    internal class ActionGroups {
        
        public static Gtk.ActionGroup GetActionGroup(System.Type type) {
            return Stetic.ActionGroups.GetActionGroup(type.FullName);
        }
        
        public static Gtk.ActionGroup GetActionGroup(string name) {
            return null;
        }
    }
}
