CSC=gmcs 
OUT=../bin/MonoTorrent.BEncoding.dll
REFERENCES=-r:System
SOURCES=AssemblyInfo.cs \
	BEncode.cs \
	BEncodedDictionary.cs \
	BEncodedList.cs \
	BEncodedNumber.cs \
	BEncodedString.cs \
	BEncodingException.cs \
	IBEncodedValue.cs

all: $(OUT)

include ../rules.make

