TARGET=-target:exe
OUT=../bin/MonoTorrent.exe

REFERENCES=\
	-r:../bin/MonoTorrent.dll	\
	-r:../Libs/Upnp.dll

SOURCES=main.cs \
	Top10Listener.cs

all: $(OUT)

include ../rules.make
TARGET=-target:exe